name: deploy

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: touch asdfasdfasdf
      - run: sudo python src/app.py & disown
